#!/usr/bin/env python3
"""Génère wallpapers.ods avec les colonnes ID | ancien_nom | nouveau_nom"""
import zipfile, io, xml.etree.ElementTree as ET

rows = [
    (1, "0eNCgs.jpg", "anime_fighter-kick-fire_orange-red.jpg"),
    (2, "1061232.jpg", "fantasy_warriors-tidal-wave_dark-teal.jpg"),
    (3, "12910.jpg", "anime_sky-aircraft-clouds_blue-pink.jpg"),
    (4, "1317019_catppuccin-mocha.png", "anime_girl-uniform-minimal_dark-navy.png"),
    (5, "1335141_catppuccin-mocha.png", "anime_jjk-characters-collage_pastel.png"),
    (6, "1340845_catppuccin-mocha.jpeg", "anime_jjk-itadori-cursed-fight_pink-teal.jpeg"),
    (7, "1345576(1)_catppuccin-mocha.jpeg", "anime_jjk-full-cast_pink-dark.jpeg"),
    (8, "1348376.png", "anime_giant-fight-silhouette_black-white.png"),
    (9, "1351306.png", "pixelart_medieval-village_blue-green.png"),
    (10, "176937.jpg", "art_desert-tree-sunset_orange-teal.jpg"),
    (11, "1969-ringbrothers-5120x2880-24457.jpg", "cars_ringbrothers-1969_dark.jpg"),
    (12, "1.jpg", "scifi_astronaut-jellyfish_dark-multicolor.jpg"),
    (13, "1mvqs59fwqwf1.png", "nature_fern-spiral-macro_green.png"),
    (14, "20250127a_black_and_white_image_of_a_room.jpeg", "manga_horror-eye-monster-window_black-white.jpeg"),
    (15, "20250127jinx-graffiti-3840x2160-19975.jpg", "anime_arcane-jinx-graffiti_colorful.jpg"),
    (16, "20250127sand.jpg", "abstract_sand-texture_black.jpg"),
    (17, "20250127wallpaper12.jpg", "abstract_dark-waves_black.jpg"),
    (18, "20250127wallpaper17.jpg", "tech_hard-drive-macro_black-white.jpg"),
    (19, "20250127wallpaper2.jpg", "nature_mountains-fog_black-white.jpg"),
    (20, "20250127wallpaper4.jpg", "nature_cracked-rock-texture_black.jpg"),
    (21, "20250127wallpaper5.jpg", "nature_mount-fuji-clouds_black-white.jpg"),
    (22, "20250127wallpaper7.jpg", "nature_waterfall-silhouette_black-white.jpg"),
    (23, "22738badf7917af94258bc5b66c298a86f75847d90681430d09f79ad8bcd5da8..jpg", "nature_forest-waterfall_green.jpg"),
    (24, "2Untitled_catppuccin-mocha.png", "anime_rooftop-summer-clouds_mocha.png"),
    (25, "2Untitled.png", "anime_rooftop-summer-clouds_blue.png"),
    (26, "303050.png", "space_ringed-planet-star_teal.png"),
    (27, "32j4hjkl4j4hkl.png", "abstract_fluid-paint_dark-pink-blue.png"),
    (28, "33tnd65l286g1.png", "art_great-wave-kanagawa_black-white.png"),
    (29, "3440x1440_fallen_angel_generated_on_moescape_ai.jpeg", "art_fallen-angel_dark-purple.jpeg"),
    (30, "[3440x1440] Solitude (Generated on Moescape AI).jpeg", "art_solitude-moescape_dark.jpeg"),
    (31, "3840x2160_almsee_lake_austria.png", "nature_almsee-lake-austria_blue-green.png"),
    (32, "3840x2160_mount_temple_canada.png", "nature_mount-temple-canada_blue.png"),
    (33, "3d-cubes-colorful-geometric-patterns-4010x2480-906.jpg", "abstract_3d-cubes_colorful.jpg"),
    (34, "3d-model.jpg", "abstract_3d-model_dark.jpg"),
    (35, "402810.jpg", "abstract_lowpoly_blue.jpg"),
    (36, "404-page_not_found.png", "tech_404-page_dark.png"),
    (37, "4.jpg", "anime_naruto-sharingan-eye_purple.jpg"),
    (38, "4k-Forest-Waterfalls-Turquoise-Lake-Landscape-Wallpaper.jpg", "nature_forest-waterfall-lake_turquoise.jpg"),
    (39, "4.png", "scifi_solar-system-diagram_dark-blue.png"),
    (40, "567890_a_color_photo_of_a_smoky_ghostly_luminous_spiritual_bein_34d0cfec-e1f3-49a7-b5dd-7acd900ef07d.png", "fantasy_crystal-ball-ice_blue-orange.png"),
    (41, "678913.jpg", "space_nebula_dark-blue.jpg"),
    (42, "67a3E2.png", "nature_mountains-above-clouds_pink-gold.png"),
    (43, "72109603_p0_master1200.jpg", "anime_demon-girl-wings-lying_white-grey.jpg"),
    (44, "8SFx.png", "anime_black-cat-closeup_dark-blue.png"),
    (45, "98a92811f408880ad5bb343c909839f72ce7238eb84ca6c0a51deb1d256b9555..jpg", "nature_karst-mountains-river-sunset_gold-orange.jpg"),
    (46, "9rzmk1ac1yqd1.jpeg", "gaming_sekiro-samurai-village_purple-grey.jpeg"),
    (47, "a_beach_with_palm_trees_and_a_moon.png", "nature_beach-palm-moon_dark.png"),
    (48, "a_bird_flying_over_a_building.jpeg", "nature_bird-flying-building_dark.jpeg"),
    (49, "a_bird_on_a_branch.jpg", "nature_bird-on-branch_colorful.jpg"),
    (50, "a_black_and_white_diagram_of_a_tree_of_life.jpg", "art_tree-of-life_black-white.jpg"),
    (51, "a_black_and_white_logo.png", "abstract_minimal-logo_black-white.png"),
    (52, "a_black_and_white_photo_of_a_city.png", "nature_city_black-white.png"),
    (53, "a_black_and_white_picture_of_mountains_and_trees.png", "nature_mountains-trees_black-white.png"),
    (54, "a_black_and_white_swirly_pattern.jpg", "abstract_swirly-pattern_black-white.jpg"),
    (55, "a_black_background_with_a_white_line_drawing_of_a_mountain_and_planets.jpg", "abstract_mountain-planets-line_black-white.jpg"),
    (56, "a_black_background_with_green_and_blue_squares.jpg", "abstract_squares_green-blue.jpg"),
    (57, "a_black_background_with_purple_and_blue_spots.png", "abstract_spots_purple-blue.png"),
    (58, "a_black_background_with_white_dots_and_circles.png", "abstract_dots-circles_black-white.png"),
    (59, "a_blue_tiger_with_black_lines_and_white_teeth.jpg", "art_tiger_blue.jpg"),
    (60, "a_boy_sleeping_on_grass_anime.png", "anime_boy-sleeping-grass_green.png"),
    (61, "a_branch_with_white_flowers.png", "nature_branch-white-flowers_white.png"),
    (62, "a_building_and_trees_at_night.jpg", "nature_building-trees-night_dark.jpg"),
    (63, "a_building_with_trees_and_stars_in_the_sky.jpg", "nature_building-stars-sky_dark.jpg"),
    (64, "a_cartoon_of_a_cat_on_a_balcony.jpeg", "anime_cat-balcony_dark.jpeg"),
    (65, "a_cartoon_of_a_girl_holding_a_book.jpg", "anime_girl-book_colorful.jpg"),
    (66, "a_cartoon_of_a_girl_holding_a_drink.png", "anime_girl-drink_colorful.png"),
    (67, "a_cartoon_of_a_girl_holding_an_umbrella.png", "anime_girl-umbrella_colorful.png"),
    (68, "a_cartoon_of_a_girl_sitting_on_a_porch_in_the_rain.png", "anime_girl-porch-rain_dark.png"),
    (69, "a_cartoon_of_a_girl_standing_next_to_a_car.jpg", "anime_girl-car_colorful.jpg"),
    (70, "a_cartoon_of_a_girl_with_blue_hair_and_a_skull.jpg", "anime_girl-blue-hair-skull_dark.jpg"),
    (71, "a_cartoon_of_a_girl_with_long_hair_holding_a_sword.jpg", "anime_girl-longhair-sword_dark.jpg"),
    (72, "a_cartoon_of_a_group_of_children.jpg", "anime_group-children_colorful.jpg"),
    (73, "a_cartoon_of_a_house_on_a_cliff.png", "anime_house-cliff_dark.png"),
    (74, "a_cartoon_of_a_island_with_a_bridge_and_trees_01.jpg", "anime_island-bridge-trees_colorful-01.jpg"),
    (75, "a_cartoon_of_a_island_with_a_bridge_and_trees_02.jpg", "anime_island-bridge-trees_colorful-02.jpg"),
    (76, "a_cartoon_of_a_whale_flying_over_a_road.jpg", "anime_whale-flying_colorful.jpg"),
    (77, "a_cartoon_of_a_woman_diving_into_a_large_wave.png", "anime_woman-diving-wave_colorful.png"),
    (78, "a_cartoon_of_a_woman_holding_a_hose_with_a_hose_in_front_of_a_swimming_pool.jpg", "anime_woman-pool_colorful.jpg"),
    (79, "a_cartoon_of_a_woman_in_a_dress.jpg", "anime_woman-dress_colorful.jpg"),
    (80, "a_cartoon_of_a_woman.png", "anime_woman_colorful.png"),
    (81, "a_cartoon_of_a_woman_with_flowers_in_her_hair.jpg", "anime_woman-flower-hair_colorful.jpg"),
    (82, "a_cartoon_of_a_woman_with_long_hair (2).jpg", "anime_woman-longhair_colorful-02.jpg"),
    (83, "a_cartoon_of_a_woman_with_long_hair.png", "anime_woman-longhair_colorful-01.png"),
    (84, "a_cartoon_of_a_woman_with_long_white_hair.jpg", "anime_woman-white-hair_colorful.jpg"),
    (85, "a_cartoon_of_people_around_a_table_with_food_and_drinks.jpg", "anime_people-table-food_colorful.jpg"),
    (86, "a_cassette_tape_with_a_message_on_it.jpg", "abstract_cassette-tape_dark.jpg"),
    (87, "a_cat_mask_with_gold_and_blue_accents.jpg", "art_cat-mask_gold-blue.jpg"),
    (88, "a_cave_in_a_rocky_area.jpg", "nature_cave-rocky_dark.jpg"),
    (89, "a_chair_on_a_platform_with_a_halo_above_it.jpg", "abstract_chair-halo_dark.jpg"),
    (90, "a_city_skyline_with_many_buildings.png", "nature_city-skyline_dark.png"),
    (91, "a_colorful_circle_with_dots.jpg", "abstract_circle-dots_multicolor.jpg"),
    (92, "a_colorful_planets_in_a_circle.jpg", "space_planets-circle_multicolor.jpg"),
    (93, "a_computer_room_with_a_desk_and_a_computer_monitor.jpg", "lofi_computer-room_dark.jpg"),
    (94, "a_couple_of_planes_flying_over_a_wave.jpg", "art_planes-wave_colorful.jpg"),
    (95, "a_deck_with_trees_and_a_railing_02.jpg", "nature_deck-trees_dark.jpg"),
    (96, "a_drawing_of_a_building.jpg", "art_building-drawing_dark.jpg"),
    (97, "a_drawing_of_an_astronaut_holding_a_rocket.jpg", "scifi_astronaut-rocket_dark.jpg"),
    (98, "a_drawing_of_an_astronaut_in_space_01.png", "scifi_astronaut-space_dark-01.png"),
    (99, "a_drawing_of_an_astronaut_in_space_02.png", "scifi_astronaut-space_dark-02.png"),
    (100, "a_drawing_of_an_astronaut_in_space_03.jpg", "scifi_astronaut-space_dark-03.jpg"),
    (101, "Adriann_back_of_a_postcard_template_watercolor_Disco_themed_827aafc7-61f6-4117-bad0-d74f97a20ee4.png", "anime_train-station-meteor-sky_blue.png"),
    (102, "adventure-hiking-cliff-night-moon-3840x2160-5272.jpg", "nature_hiking-cliff-moon_dark.jpg"),
    (103, "a_flower_on_a_dark_background.png", "nature_flower_dark.png"),
    (104, "a_graphic_of_a_clock_with_an_egyptian_symbol.jpg", "abstract_clock-egyptian_dark.jpg"),
    (105, "a_group_of_buildings_with_neon_lights_01.png", "art_neon-buildings_dark-01.png"),
    (106, "a_group_of_buildings_with_neon_lights_02.png", "art_neon-buildings_dark-02.png"),
    (107, "a_group_of_cartoon_characters_01.jpg", "anime_group-characters_colorful.jpg"),
    (108, "a_group_of_colorful_ghosts.png", "gaming_colorful-ghosts_colorful.png"),
    (109, "akaza-vs-tanjiro-6400x5223-23616.jpg", "anime_demon-slayer-akaza-vs-tanjiro_dark-red.jpg"),
    (110, "alien-planet-5120x3657-22104.jpg", "space_alien-planet_dark-purple.jpg"),
    (111, "Animated_Land.jpg", "anime_countryside-meadow-summer_blue-green.jpg"),
    (112, "Anime-City-Night.png", "anime_city-night_dark.png"),
    (113, "anime-demon-girl-samurai-katana-4k-wallpaper.jpg", "anime_demon-girl-samurai_dark.jpg"),
    (114, "Anime-Fireworks.png", "anime_fireworks_colorful.png"),
    (115, "Anime_girl_closeup_cat_green.jpg", "anime_girl-cat-closeup_green.jpg"),
    (116, "Anime-girls-dragon-shadowverse-arisa-shadowverse.png", "anime_shadowverse-arisa-dragon_colorful.png"),
    (117, "Anime Girl Student Gazing at the Sky with Clouds [1920x1080].jpeg", "anime_student-girl-sky_blue.jpeg"),
    (118, "Anime-Japan-Street.png", "anime_japan-street_dark.png"),
    (119, "anime-yakuza-yokai-mask-katana-4k-wallpaper.jpg", "anime_yakuza-yokai-mask_dark.jpg"),
    (120, "anonymous-hacker-data-breach-5k-6000x4004-7.jpg", "tech_hacker-data-breach_dark.jpg"),
    (121, "Antonio Canaletto's View of the Arch of Constantine with the Colosseum.jpg", "art_canaletto-colosseum_warm.jpg"),
    (122, "Arcade_decay_red.png", "abstract_arcade-decay_red.png"),
    (123, "arc-vector-electric-bikes-future-bikes-prototype-dark-8000x4500-3376.jpg", "cars_arc-vector-electric-bike_dark.jpg"),
    (124, "ARR02.png", "anime_ghibli-tree-sunlight_green.png"),
    (125, "artemis-ii-nasa-5k-5200x3250-25357.jpg", "space_nasa-artemis_dark.jpg"),
    (126, "ARTWORK-wanderer-above-the-sea-of-fog.jpg", "art_wanderer-sea-of-fog_grey.jpg"),
    (127, "Asher Brown Durand's Thanatopsis.jpg", "art_durand-thanatopsis_green.jpg"),
    (128, "assassins-creed-pigeons-desktop-wallpaper.jpg", "gaming_assassins-creed-pigeons_dark.jpg"),
    (129, "asta-black-clover-4k-wallpaper.jpg", "anime_black-clover-asta_dark.jpg"),
    (130, "astronaut-hanging-3840x2160-16246.png", "space_astronaut-hanging_dark.png"),
    (131, "asus-rog-8k-amoled-7680x4320-15686.png", "tech_asus-rog_black.png"),
    (132, "asus-tuf-gaming-5120x2880-25680.jpg", "tech_asus-tuf_dark.jpg"),
    (133, "avengers-doomsday-5120x2880-24974.jpg", "marvel_avengers-doomsday_dark.jpg"),
    (134, "Background3.png", "anime_schoolgirl-sitting-alone_teal.png"),
    (135, "Backyard.png", "anime_onsen-backyard-night_blue.png"),
    (136, "batman-gotham-city-4k-wallpaper.jpg", "dc_batman-gotham_dark.jpg"),
    (137, "batman-sign-black-background-dc-superheroes-amoled-5k-8k-10k-10000x6250-4409.jpg", "dc_batman-logo_black.jpg"),
    (138, "Beer-Girl.png", "anime_beer-girl_colorful.png"),
    (139, "bfx14db7qcig1.png", "nature_moon-field-reflection_dark-blue.png"),
    (140, "black-and-white-6480x7454-21293.jpg", "nature_desert-sand-dunes_black-white.jpg"),
    (141, "Black Panther.jpg", "marvel_black-panther_dark-01.jpg"),
    (142, "black-panther-lexus-lc-500-digital-art-neon-art-marvel-5120x3348-8298.jpg", "marvel_black-panther-car-neon_dark.jpg"),
    (143, "black-panther-marvel-superheroes-black-background-amoled-5k-5200x2936-8375.jpg", "marvel_black-panther_black-02.jpg"),
    (144, "black-panther-marvel-superheroes-black-background-amoled-5k-5280x2924-8385.jpg", "marvel_black-panther_black-03.jpg"),
    (145, "blue-abstract-5120x2880-25119.jpg", "abstract_blue_blue.jpg"),
    (146, "Bluepink-both.png", "abstract_blue-pink_blue-pink.png"),
    (147, "bmw-m3-angel-eyes-black-background-5k-5000x3000-896.jpg", "cars_bmw-m3-angel-eyes_black.jpg"),
    (148, "Bonsai-Plant.png", "nature_bonsai_dark.png"),
    (149, "Captain America.jpg", "marvel_captain-america_dark.jpg"),
    (150, "cat-coffee-chill-pond-4k-wallpaper.jpg", "lofi_cat-coffee-chill_dark.jpg"),
    (151, "CatppuccinMocha-Kurzgesagt-BlackHole3.png", "space_kurzgesagt-blackhole_dark-mocha.png"),
    (152, "cats-moon-pink-silhouette-black-background-3840x2880-978.png", "nature_cats-moon-silhouette_pink.png"),
    (153, "ccc_got_10.jpg", "serie_got-iron-throne-tree_black-white.jpg"),
    (154, "ccc_got_1.jpg", "serie_got-jon-snow-ghost_red-dark.jpg"),
    (155, "ccc_got_2.jpg", "serie_got_dark-02.jpg"),
    (156, "ccc_got_3.jpg", "serie_got_dark-03.jpg"),
    (157, "ccc_got_4.jpg", "serie_got_dark-04.jpg"),
    (158, "ccc_got_5.jpg", "serie_got-arya-faces_white-dark.jpg"),
    (159, "ccc_got_6.jpg", "serie_got_dark-06.jpg"),
    (160, "ccc_got_7.jpg", "serie_got_dark-07.jpg"),
    (161, "ccc_got_8.jpg", "serie_got_dark-08.jpg"),
    (162, "ccc_got_9.jpg", "serie_got_dark-09.jpg"),
    (163, "chainsaw-man-the-5120x2880-23013.jpg", "anime_chainsaw-man_dark.jpg"),
    (164, "choso-red-aesthetic-5120x2880-26047.jpg", "anime_jjk-choso_red.jpg"),
    (165, "City-Rain.png", "art_city-rain_dark.png"),
    (166, "Courtside-Sunset.png", "lofi_courtside-sunset_orange.png"),
    (167, "cristiano-ronaldo-3840x2160-17331.jpg", "sport_cristiano-ronaldo_dark.jpg"),
    (168, "dandelion-flower-5120x2880-26268.jpg", "nature_dandelion_dark.jpg"),
    (169, "daredevil-born-5120x2880-26083.jpg", "marvel_daredevil_dark-01.jpg"),
    (170, "daredevil-born-5120x2880-26084.jpg", "marvel_daredevil_dark-02.jpg"),
    (171, "daredevil-born-6000x3407-25420.jpg", "marvel_daredevil_dark-03.jpg"),
    (172, "dark-background-abstract-background-network-3d-background-7680x4320-8324.png", "abstract_network-3d_dark.png"),
    (173, "Dark_Nature.png", "nature_dark-nature_dark.png"),
    (174, "darth-vader-black-background-star-wars-lightsaber-amoled-3840x2160-4971.jpg", "scifi_starwars-vader-lightsaber_black.jpg"),
    (175, "darth-vader-death-5120x2880-22737.jpg", "scifi_starwars-vader-death_dark.jpg"),
    (176, "darth-vader-violin-lightsaber-amoled-black-background-3840x2160-4953.png", "scifi_starwars-vader-violin_black.png"),
    (177, "deer-silhouette-moon-night-minimal-art-illustration-dark-3840x2160-5717.jpg", "nature_deer-silhouette-moon_dark.jpg"),
    (178, "deer-silhouette-sun-dark-background-3840x2880-974.png", "nature_deer-silhouette-sun_dark.png"),
    (179, "desert-doom-sand-dunes-dark-background-monochrome-landscape-3840x2160-6409.jpg", "nature_desert-sand-dunes_dark.jpg"),
    (180, "Dessert-Dark.png", "nature_dark-desert_dark.png"),
    (181, "divine-general-mahoraga.jpg", "anime_jjk-mahoraga_grey.jpg"),
    (182, "dope-sukuna-pink-5120x2880-16935.png", "anime_jjk-sukuna_pink.png"),
    (183, "Dreamy-Aesthetic-Home-Under-Moonlight.png", "lofi_home-moonlight_dark.png"),
    (184, "Dr Strange.jpg", "marvel_dr-strange_dark.jpg"),
    (185, "ducati-superleggera-7680x4320-26088.jpg", "cars_ducati-superleggera_dark.jpg"),
    (186, "ducduj3qld8g1.png", "nature_milkyway-lake-flowers_dark-blue.png"),
    (187, "earth-mars-planet-space-8k-wallpaper.jpg", "space_earth-mars_dark.jpg"),
    (188, "_eclipse_protocol__by_evlsound_dis46a5-fullview.jpg", "scifi_eclipse-protocol_dark.jpg"),
    (189, "eren-attack-on-titan-4k-wallpaper.jpg", "anime_aot-eren_dark.jpg"),
    (190, "EVA.jpg", "anime_evangelion-crosses-eva_dark-red.jpg"),
    (191, "fail-but-never-quit-failure-never-give-up-motivational-8800x5000-7693.jpg", "motivational_never-give-up_dark.jpg"),
    (192, "Fantasy-Autumn.png", "art_fantasy-autumn_orange.png"),
    (193, "Fantasy-IcyMountain.png", "art_fantasy-icy-mountain_blue.png"),
    (194, "Fantasy-Japanese-Street.png", "art_fantasy-japanese-street_dark.png"),
    (195, "Fantasy-Lake1.png", "art_fantasy-lake_blue-01.png"),
    (196, "Fantasy-Lake2.png", "art_fantasy-lake_blue-02.png"),
    (197, "Fantasy-Lake3.png", "art_fantasy-lake_blue-03.png"),
    (198, "Fantasy-Landscape1.png", "art_fantasy-landscape_colorful-01.png"),
    (199, "Fantasy-Landscape2.png", "art_fantasy-landscape_colorful-02.png"),
    (200, "Fantasy-Landscape3.png", "art_fantasy-landscape_colorful-03.png"),
    (201, "Fantasy-Lanscape-Night.png", "art_fantasy-landscape-night_dark.png"),
    (202, "Fantasy-Snow-Valley.png", "art_fantasy-snow-valley_white-blue.png"),
    (203, "__feixiao_and_flying_aureus_honkai_and_1_more_drawn_by_swkl_d__5e0d01fc5e555f50bf0bba9a58500afc.jpg", "anime_honkai-feixiao-feathers_blue-red.jpg"),
    (204, "fighter-jet-pilot-5120x2880-24341.png", "scifi_fighter-jet-pilot_dark.png"),
    (205, "fireplace.gif", "lofi_fireplace_warm.gif"),
    (206, "Flowers, text, noise, HD wallpaper.jpg", "art_flowers-text_colorful.jpg"),
    (207, "fmuAamg.jpg", "art_mount-fuji-city-night_teal-pink.jpg"),
    (208, "Forest-Dark.png", "nature_dark-forest_dark.png"),
    (209, "Forest-Waterfalls-Turquoise-Lake-Landscape-Wallpaper-1081x608.jpg", "nature_forest-waterfall-lake_turquoise-02.jpg"),
    (210, "fox-graveyard-art-4k-wallpaper.jpg", "art_fox-graveyard_dark.jpg"),
    (211, "Fratal_clouds.jpg", "abstract_fractal-spiral_red-teal.jpg"),
    (212, "frieren-beyond-3840x2160-24988.jpg", "anime_frieren-beyond_dark.jpg"),
    (213, "Fruit-du-Demon-Bleu-4K.jpg", "anime_one-piece-devil-fruit-blue_dark-4k.jpg"),
    (214, "Fruit-du-Demon-Bleu-Banniere.jpg", "anime_one-piece-devil-fruit-blue_banner.jpg"),
    (215, "Fruit-du-Demon-Bleu-Desktop.jpg", "anime_one-piece-devil-fruit-blue_desktop.jpg"),
    (216, "Fruit-du-Demon-Bleu.jpg", "anime_one-piece-devil-fruit-blue_dark.jpg"),
    (217, "Fruit-du-Demon-Rose-4K.jpg", "anime_one-piece-devil-fruit-rose_pink-4k.jpg"),
    (218, "Fruit-du-Demon-Rose-Banniere.jpg", "anime_one-piece-devil-fruit-rose_banner.jpg"),
    (219, "Fruit-du-Demon-Rose-Desktop.jpg", "anime_one-piece-devil-fruit-rose_desktop.jpg"),
    (220, "Fruit-du-Demon-Rose.jpg", "anime_one-piece-devil-fruit-rose_pink.jpg"),
    (221, "Game-GTA.png", "gaming_gta_dark.png"),
    (222, "genshin-impact-5120x2880-25525.png", "gaming_genshin-impact_colorful.png"),
    (223, "Ghost Rider.jpg", "marvel_ghost-rider_dark.jpg"),
    (224, "giyu-tomioka-amoled-3840x2160-22604.png", "anime_demon-slayer-giyu-tomioka_black.png"),
    (225, "GMJLlQ9qg5.jpg", "anime_darling-franxx-02-night_purple.jpg"),
    (226, "gojo-eyes-jujutsu-kaisen-4k-wallpaper.jpg", "anime_jjk-gojo-eyes_blue.jpg"),
    (227, "goku-perfected-5120x2880-25454.jpg", "anime_dragonball-goku_dark.jpg"),
    (228, "gon-hunter-x-hunter-4k-wallpaper.jpg", "anime_hxh-gon_dark-01.jpg"),
    (229, "Grand Theft Auto V Wallpaper (10).jpg", "gaming_gta5_dark-01.jpg"),
    (230, "Grand Theft Auto V Wallpaper (12).jpg", "gaming_gta5_dark-02.jpg"),
    (231, "Grand Theft Auto V Wallpaper (19).jpg", "gaming_gta5_dark-03.jpg"),
    (232, "Grand Theft Auto V Wallpaper (1).jpg", "gaming_gta5_dark-04.jpg"),
    (233, "Grand Theft Auto V Wallpaper (22).jpg", "gaming_gta5_dark-05.jpg"),
    (234, "Grand Theft Auto V Wallpaper (23).jpg", "gaming_gta5_dark-06.jpg"),
    (235, "Grand Theft Auto V Wallpaper (4).jpg", "gaming_gta5_dark-07.jpg"),
    (236, "Grand Theft Auto V Wallpaper (9).jpg", "gaming_gta5_dark-08.jpg"),
    (237, "gunther-werks-turbo-7680x4320-25939.jpg", "cars_gunther-werks-turbo_dark.jpg"),
    (238, "guts-artwork-5120x2880-21418.jpg", "anime_berserk-guts_dark-01.jpg"),
    (239, "guts-berserk-4k-wallpaper.jpg", "anime_berserk-guts_dark-02.jpg"),
    (240, "guts-black-5120x2880-21420.png", "anime_berserk-guts_black.png"),
    (241, "guts-neon-iconic-5120x2880-21415.png", "anime_berserk-guts-neon_dark.png"),
    (242, "hatsune-miku-5644x2880-22725.jpg", "anime_vocaloid-miku_blue.jpg"),
    (243, "hatsune-miku-error-anime-girl-4k-wallpaper.jpg", "anime_vocaloid-miku-error_dark.jpg"),
    (244, "hello-kitty-amoled-5120x2880-25116.png", "anime_hello-kitty_black.png"),
    (245, "hello-world-pixel-7680x4320-15168.png", "tech_hello-world-pixel_dark.png"),
    (246, "hollow-knight-game-4k-wallpaper.jpg", "gaming_hollow-knight_dark.jpg"),
    (247, "Hulk.jpg", "marvel_hulk_green.jpg"),
    (248, "hunter-x-hunter-gon-5120x2880-10409.png", "anime_hxh-gon_dark-02.png"),
    (249, "igris-solo-leveling-4k-wallpaper.jpg", "anime_solo-leveling-igris_dark.jpg"),
    (250, "imu-one-piece-4k-wallpaper.jpg", "anime_one-piece-imu_dark-01.jpg"),
    (251, "imu-one-piece-anime-4k-wallpaper.jpg", "anime_one-piece-imu_dark-02.jpg"),
    (252, "iron-man-8k-wallpaper.jpg", "marvel_iron-man_dark-01.jpg"),
    (253, "Iron Man .jpg", "marvel_iron-man_dark-02.jpg"),
    (254, "island-night-moon-scenery-digital-art-8k-wallpaper.jpg", "nature_island-night-moon_dark.jpg"),
    (255, "itachi-uchiha-10k-10000x7500-25772.jpg", "anime_naruto-itachi_dark-01.jpg"),
    (256, "itachi-uchiha-5120x2880-25576.png", "anime_naruto-itachi_dark-02.png"),
    (257, "itachi-uchiha-naruto-amoled-black-background-minimal-art-3840x2160-6478.jpg", "anime_naruto-itachi-minimal_black.jpg"),
    (258, "itadori-yuuji-5120x2880-9272.jpg", "anime_jjk-itadori_dark-04.jpg"),
    (259, "IT_guy.png", "lofi_hacker-server-room_dark-green.png"),
    (260, "j0kp1ywmsw8g1.png", "nature_mountain-aurora-waterfall_purple-teal.png"),
    (261, "japan-artistic-5120x2880-25406.jpg", "art_japan-artistic_dark.jpg"),
    (262, "jinx-arcane-neon-5120x2880-19860.jpg", "anime_arcane-jinx-neon_dark.jpg"),
    (263, "joyboy-meeting-imu-sama-visualisation-v0-gg0kcm567pg71.png", "anime_one-piece-joyboy-imu_dark.png"),
    (264, "Jz3pJwB.jpg", "anime_frieren-two-mages-field_teal-blue.jpg"),
    (265, "kame-house-dragon-5120x2880-25003.jpg", "anime_dragonball-kame-house_dark.jpg"),
    (266, "kazutora-hanemiya-5120x2880-21416.png", "anime_tokyo-rev-kazutora_dark.png"),
    (267, "killua-hunter-x-hunter-broken-screen-4k-wallpaper.jpg", "anime_hxh-killua_dark.jpg"),
    (268, "koi-fish-pond-art-4k-wallpaper.jpg", "art_koi-fish-pond_colorful.jpg"),
    (269, "kylo-ren-star-wars-lightsaber-fictional-character-armor-red-6290x3565-6732.jpg", "scifi_starwars-kylo-ren_dark-red.jpg"),
    (270, "Lain-Iwakura-Serial-Experiments-Lain-2232276.png", "anime_lain_dark.png"),
    (271, "LainTheme3.jpg", "anime_lain-pixel-eye-pattern_black-pink.jpg"),
    (272, "lavender-fields-5120x2880-21314.jpg", "nature_lavender-fields_purple.jpg"),
    (273, "Linux-user-Room.png", "lofi_linux-user-room_dark.png"),
    (274, "lofi-anime-girl-cat-chill-headphone-4k-wallpaper.jpg", "lofi_anime-girl-cat-headphone_dark.jpg"),
    (275, "Lofi - Chill Room2.jpeg", "lofi_chill-room_dark-01.jpeg"),
    (276, "Lofi - Chill Room.png", "lofi_chill-room_dark-02.png"),
    (277, "Lofi-Room.png", "lofi_chill-room_dark-03.png"),
    (278, "Loki.jpg", "marvel_loki_green.jpg"),
    (279, "Lowpoly_Street_tokyo_japan.png", "art_tokyo-street-lowpoly_colorful.png"),
    (280, "luffy-one-piece-4k-wallpaper.jpg", "anime_one-piece-luffy_dark.jpg"),
    (281, "luffy-one-piece-elbaph-arc-4k-wallpaper.jpg", "anime_one-piece-luffy-elbaph_dark-01.jpg"),
    (282, "luffy-one-piece-elbaph-arc-4k-wallpaperr.jpg", "anime_one-piece-luffy-elbaph_dark-02.jpg"),
    (283, "Manga-Portal.png", "manga_portal_dark.png"),
    (284, "Manga-Shrine.png", "manga_shrine_dark.png"),
    (285, "Mecha-Nostalgia.png", "anime_mecha-nostalgia_dark.png"),
    (286, "metro-2039-4k-wallpaper.jpg", "gaming_metro-2039_dark.jpg"),
    (287, "miles-morales-red-5120x2880-22574.png", "marvel_spiderman-miles-morales_red.png"),
    (288, "minecraft-zombie-4k-wallpaper.jpg", "gaming_minecraft-zombie_dark.jpg"),
    (289, "Minimal_Squares.png", "abstract_minimal-squares_colorful.png"),
    (290, "mitsuha-miyamizu-5120x2880-14910.jpg", "anime_your-name-mitsuha_dark.jpg"),
    (291, "miyamoto-musashi-3840x2160-15204.jpg", "anime_miyamoto-musashi_dark-01.jpg"),
    (292, "miyamoto-musashi-5k-5120x2880-15210.jpg", "anime_miyamoto-musashi_dark-02.jpg"),
    (293, "ml1 (copie 1).jpeg", "art_mountain-lake-dock-night_dark-blue-copy.jpeg"),
    (294, "ml1.jpeg", "art_mountain-lake-dock-night_dark-blue.jpeg"),
    (295, "ml2 (copie 1).jpeg", "art_mountain-lake-dock-night_dark-red-copy.jpeg"),
    (296, "ml2.jpeg", "art_mountain-lake-dock-night_dark-red.jpeg"),
    (297, "ml3 (copie 1).jpeg", "art_mountain-lake-dock-night_dark-teal-copy.jpeg"),
    (298, "ml3.jpeg", "art_mountain-lake-dock-night_dark-teal.jpeg"),
    (299, "ml4 (copie 1).jpeg", "art_mountain-lake-dock-night_orange-dark-copy.jpeg"),
    (300, "ml4.jpeg", "art_mountain-lake-dock-night_orange-dark.jpeg"),
    (301, "ml5.jpeg", "art_mountain-lake-dock-night_purple.jpeg"),
    (302, "ml6.jpeg", "art_mountain-lake-dock-night_green.jpeg"),
    (303, "mob-psycho-100-4k-wallpaper.jpg", "anime_mob-psycho_dark.jpg"),
    (304, "Mocha-hald10-03.jpg.jpg", "abstract_topographic-waves_dark-pink.jpg"),
    (305, "Mocha-hald10-08.jpg.jpg", "abstract_spiral-vortex_dark-pink.jpg"),
    (306, "monkey-d-luffy-red-5120x2880-24473.png", "anime_one-piece-luffy_red.png"),
    (307, "Monsters_Moon_Night_Fantasy_skull_skulls_demon_demon_reaper_4039x2126.jpg", "fantasy_monsters-moon-skull_dark.jpg"),
    (308, "moon-coloros-stock-astronomy-black-background-4680x2160-358.jpg", "space_moon-colored_dark.jpg"),
    (309, "moonlight-7680x4320-11080.jpg", "nature_moonlight_dark.jpg"),
    (310, "moon-planet-8k-7680x4320-87.jpg", "space_moon-planet_dark.jpg"),
    (311, "Mountain_01.png", "art_mountain_dark.png"),
    (312, "muichiro-tokito-5120x2880-23644.jpg", "anime_demon-slayer-muichiro_blue.jpg"),
    (313, "naruto-digital-art-black-background-amoled-3840x2160-5056.png", "anime_naruto-digital_black.png"),
    (314, "Night_5760x2880px2.png", "nature_night-wide_dark.png"),
    (315, "nightcore-anime-girl-wings-angel-with-a-shotgun-4k-wallpaper.jpg", "anime_angel-girl-wings-shotgun_dark.jpg"),
    (316, "nihilist-penguin-5120x2880-25229.jpg", "anime_nihilist-penguin_dark.jpg"),
    (317, "NintendoSwitch2_Hollow_Knight_Silksong_KeyArt2.png", "gaming_hollow-knight-silksong_dark.png"),
    (318, "Nord-Gif-Futuristic.gif", "abstract_futuristic-nord_dark.gif"),
    (319, "ocean-car-floating-full-moon-scenery-digital-art-4k-wallpaper.jpg", "art_car-ocean-moon_dark.jpg"),
    (320, "one-punch-man-saitama-amoled-black-background-5k-5120x2880-5031.png", "anime_one-punch-man-saitama_black.png"),
    (321, "__original_drawn_by_mac_star__3e313866d6435f61f819d1d6123ab981.jpg", "anime_girl-sakura-lying_dark-pink.jpg"),
    (322, "Pastel-Window.png", "lofi_pastel-window_pastel.png"),
    (323, "Patterns.png", "abstract_patterns_colorful.png"),
    (324, "planet-earth-night-view-illuminated-orbit-dark-background-5k-6000x2500-8934.jpg", "space_earth-night-orbit_dark.jpg"),
    (325, "planet-orbit-outer-space-cosmos-distant-planet-4096x3112-8763.jpg", "space_planet-orbit_dark.jpg"),
    (326, "pokemon-ball-house-anime-digital-art-4k-wallpaper.jpg", "anime_pokemon-ball-house_colorful.jpg"),
    (327, "porsche-911-5120x2880-13014.jpg", "cars_porsche-911_dark-01.jpg"),
    (328, "porsche-911-gt3-rs-3840x2160-20432.png", "cars_porsche-911-gt3-rs_dark-01.png"),
    (329, "porsche-911-gt3-rs-4000x3000-22867.jpg", "cars_porsche-911-gt3-rs_dark-02.jpg"),
    (330, "PTTJt5UDOS8QbmGeh7BclhhjPrV41Q.jpg", "anime_girl-wheat-field-clouds_gold-blue.jpg"),
    (331, "Purple Anime Girl - 4K Ultra HD Wallpaper by CelestialCanvas.png", "anime_girl-purple_purple.png"),
    (332, "qagh3qstvi7g1.png", "aesthetic_vaporwave-cyberpunk-collage_green.png"),
    (333, "Radahn.png", "gaming_elden-ring-radahn_dark.png"),
    (334, "Red_Eclipse.png", "abstract_red-eclipse_red.png"),
    (335, "re-zero-subaru-4k-wallpaper.jpg", "anime_rezero-subaru_dark.jpg"),
    (336, "road-mountains-tarmac-sunrise-morning-macos-big-sur-stock-5k-6016x6016-3996.jpg", "nature_mountain-road-sunrise_orange.jpg"),
    (337, "roronoa-zoro-green-5120x2880-18358.jpg", "anime_one-piece-zoro_green.jpg"),
    (338, "roronoa-zoro-one-piece-4k-wallpaper.jpg", "anime_one-piece-zoro_dark-01.jpg"),
    (339, "samurai-silhouette-5120x2880-24349.png", "art_samurai-silhouette_dark.png"),
    (340, "sasuke-uchiha-12k-11520x6480-25568.jpg", "anime_naruto-sasuke_dark-01.jpg"),
    (341, "sasuke-uchiha-naruto-minimal-art-amoled-black-background-5120x2880-8859.png", "anime_naruto-sasuke-minimal_black.png"),
    (342, "satoru-gojo-amoled-5120x2880-16769.jpg", "anime_jjk-gojo_black.jpg"),
    (343, "satoru-gojo-jujutsu-kaisen-4k-wallpaper.jpg", "anime_jjk-gojo_blue.jpg"),
    (344, "satoru-gojo-suguru-5120x2880-16373.png", "anime_jjk-gojo-geto_dark.png"),
    (345, "scenic-moon-5120x2880-11273.jpg", "nature_scenic-moon_dark.jpg"),
    (346, "scream-7-ghostface-8k-wallpaper.jpg", "horror_scream7-ghostface_dark.jpg"),
    (347, "sekiro-shadow-die-twice-4k-wallpaper.jpg", "gaming_sekiro_dark.jpg"),
    (348, "shanks-5k-one-piece-5120x2880-18352.jpg", "anime_one-piece-shanks_dark-01.jpg"),
    (349, "shanks.png", "anime_one-piece-shanks_dark-02.png"),
    (350, "shinobu-kocho-5120x2880-19754.jpg", "anime_demon-slayer-shinobu_purple.jpg"),
    (351, "Silksong_Sea_of_Sorrow.jpg", "gaming_hollow-knight-silksong-sea_dark.jpg"),
    (352, "space-shuttle-nasa-3456x5184-11636.jpg", "space_nasa-shuttle_dark.jpg"),
    (353, "spider-man-5120x2880-21603.jpg", "marvel_spiderman_dark-01.jpg"),
    (354, "spider-man-across-7680x4320-11476.png", "marvel_spiderman-across_dark.png"),
    (355, "spider-man-dark-cyan-minimal-3840x2160-170.jpg", "marvel_spiderman-minimal_dark-cyan.jpg"),
    (356, "spider-man-dark-red-minimal-3840x2160-167.jpg", "marvel_spiderman-minimal_dark-red.jpg"),
    (357, "Spiderman.jpg", "marvel_spiderman_dark-02.jpg"),
    (358, "spider-man-logo-red-background-5k-8k-7680x4320-7214.png", "marvel_spiderman-logo_red.png"),
    (359, "spider-man-marvel-6000x4000-11025.jpg", "marvel_spiderman_dark-03.jpg"),
    (360, "spider-man-neon-art-black-background-marvel-superheroes-5k-5600x3079-2758.png", "marvel_spiderman-neon_black.png"),
    (361, "spider-noir-series-background-8k-wallpaper.jpg", "marvel_spiderman-noir_dark.jpg"),
    (362, "sports-car-mountains-retrowave-synthwave-4k-wallpaper.jpg", "cars_sports-car-retrowave_purple-pink.jpg"),
    (363, "sports-car-racing-4k-wallpaper.jpg", "cars_sports-car-racing_dark.jpg"),
    (364, "sports-car-supercar-4k-wallpaper.jpg", "cars_supercar_dark.jpg"),
    (365, "star-wars-the-7680x4320-26293.jpg", "scifi_starwars_dark.jpg"),
    (366, "sub-zero-scorpion-5120x2880-17601.jpg", "gaming_mk-sub-zero-scorpion_dark.jpg"),
    (367, "suguro-geto-jjk-8k-wallpaper.jpg", "anime_jjk-geto_dark.jpg"),
    (368, "sukuna-action-3840x2160-25100.jpg", "anime_jjk-sukuna-action_dark.jpg"),
    (369, "sukuna-jujutsu-kaisen-4k-wallpaper.jpg", "anime_jjk-sukuna_dark.jpg"),
    (370, "sung-jinwoo-dragon-3840x2160-15351.jpg", "anime_solo-leveling-jinwoo-dragon_dark.jpg"),
    (371, "sung-jinwoo-vs-beru-solo-leveling-4k-wallpaper.jpg", "anime_solo-leveling-jinwoo-vs-beru_dark.jpg"),
    (372, "superman-dark-7680x4320-24811.jpg", "dc_superman_dark.jpg"),
    (373, "tanjiro-kamado-5120x2880-18345.png", "anime_demon-slayer-tanjiro_dark.png"),
    (374, "Thanos .jpg", "marvel_thanos_dark.jpg"),
    (375, "the-batman-part-ii-5120x2880-26470.png", "dc_batman-part2_dark.png"),
    (376, "the-flash-neon-art-purple-background-multicolor-5k-5120x2880-5268.jpg", "dc_flash-neon_purple.jpg"),
    (377, "The -Great-Wave-Of-Kanagawa.png", "art_great-wave-kanagawa_blue.png"),
    (378, "titus-warhammer-40k-5120x2880-26257.jpg", "gaming_warhammer-titus_dark.jpg"),
    (379, "todo-list-nothing-5120x2880-10079.jpg", "humor_todo-nothing-red-panda_black.jpg"),
    (380, "Tokyo_Pink.png", "art_tokyo-pink_pink.png"),
    (381, "torii-gate-alone-mountain-scenery-digital-art-4k-wallpaper.jpg", "art_torii-gate-mountain_dark.jpg"),
    (382, "TouhouShameimaru AyaInubashiri Momiji.jpg", "anime_touhou-aya-momiji_green.jpg"),
    (383, "Tower-Night.png", "art_tower-night_dark.png"),
    (384, "Tree_01.png", "nature_tree_dark-01.png"),
    (385, "Tree_02.png", "nature_tree_dark-02.png"),
    (386, "TreeField.jpg", "nature_lone-tree-field-sunset_orange.jpg"),
    (387, "t-rex-moon-5120x2880-13437.png", "art_t-rex-moon_dark.png"),
    (388, "tusk-solo-leveling-4k-wallpaper.jpg", "anime_solo-leveling-tusk_dark.jpg"),
    (389, "U87654ntitled.png", "anime_demon-samurai-mask_dark.png"),
    (390, "Unti2tl3ed.png", "anime_magical-girl-star_blue.png"),
    (391, "Untitl9765432ed.png", "fantasy_cave-sunset-figure_purple-orange.png"),
    (392, "Untitled8_catppuccin-mocha.png", "anime_two-girls-machinery_grey.png"),
    (393, "Wallpaper Alchemy - Frieren Forest Waterfall Anime Wallpaper 4K.jpg", "anime_frieren-forest-waterfall_green.jpg"),
    (394, "Wallpaper Alchemy - Frieren Melancholic Portrait Wallpaper 4K.png", "anime_frieren-melancholic_dark.png"),
    (395, "wallpaperflare.com_wallpaper(1).jpg", "tech_linux-system-godfather-tux_dark.jpg"),
    (396, "wallpaperflare.com_wallpaper(2).jpg", "tech_no-place-like-localhost_black.jpg"),
    (397, "wallpaperflare.com_wallpaper.jpg", "tech_arch-linux-logo_dark.jpg"),
    (398, "Wallpaper.png", "gaming_pacman-ghosts-minimal_dark-blue.png"),
    (399, "wallpapersden.com_frieren-hd-frieren-beyond-journey-s-end_4500x2761.jpg", "anime_frieren-beyond-journey_blue.jpg"),
    (400, "WhiteMount1.png", "nature_white-mountain_white-01.png"),
    (401, "WhiteMount2.jpg", "nature_white-mountain_white-02.jpg"),
    (402, "wolf-howling-silhouette-black-background-blue-3840x2880-975.png", "nature_wolf-howling-silhouette_dark-blue.png"),
    (403, "xoazbpym3gkg1.jpeg", "art_yosemite-waterfall-sunset_orange.jpeg"),
    (404, "y0eiummi1irf1.jpeg", "space_moon-closeup_dark-grey.jpeg"),
    (405, "yasuke-dark-7680x4320-21997.jpg", "anime_yasuke_dark.jpg"),
    (406, "your-name-couple-3840x2160-25439.jpg", "anime_your-name-couple_dark.jpg"),
    (407, "your-name-shooting-7680x4320-14938.jpg", "anime_your-name-shooting-star_blue.jpg"),
    (408, "yuji-itadori-5120x2880-9268.jpg", "anime_jjk-itadori_dark-01.jpg"),
    (409, "yuji-itadori-5120x2880-9271.jpg", "anime_jjk-itadori_dark-02.jpg"),
    (410, "yuji-itadori-5120x2880-9286.jpg", "anime_jjk-itadori_dark-03.jpg"),
    (411, "yuji-itadori-x-yuta-7680x4320-25001.jpg", "anime_jjk-itadori-yuta_dark.jpg"),
    (412, "yuji-vs-mahito-jujutsu-kaisen-modulo-4k-wallpaper.jpg", "anime_jjk-itadori-vs-mahito_dark.jpg"),
    (413, "ZGXcBF.png", "space_black-hole_gold-black.png"),
    (414, "zoro-one-piece-4k-wallpaper.jpg", "anime_one-piece-zoro_dark-02.jpg"),
    (415, "zoro-one-piece-4k-wallpaperr.jpg", "anime_one-piece-zoro_dark-03.jpg"),
]

# ── Vérification des doublons ──────────────────────────────────────────────────
new_names = [r[2] for r in rows]
seen = {}
dups = []
for r in rows:
    n = r[2]
    if n in seen:
        dups.append((seen[n], r[0], n))
    else:
        seen[n] = r[0]
if dups:
    print("⚠️  DOUBLONS DÉTECTÉS :")
    for d in dups:
        print(f"  IDs {d[0]} et {d[1]} → {d[2]}")
else:
    print(f"✅  Aucun doublon ({len(rows)} entrées)")

# ── Génération ODS (ZIP + XML) ─────────────────────────────────────────────────
def esc(s):
    return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;").replace('"',"&quot;")

def cell(val, val_type="string"):
    if val_type == "float":
        return f'<table:table-cell office:value-type="float" office:value="{val}"><text:p>{val}</text:p></table:table-cell>'
    return f'<table:table-cell office:value-type="string"><text:p>{esc(str(val))}</text:p></table:table-cell>'

rows_xml = []
# header
rows_xml.append(
    "<table:table-row>"
    + cell("ID") + cell("ancien_nom") + cell("nouveau_nom")
    + "</table:table-row>"
)
for r in rows:
    rows_xml.append(
        "<table:table-row>"
        + cell(r[0], "float") + cell(r[1]) + cell(r[2])
        + "</table:table-row>"
    )

content_xml = """<?xml version="1.0" encoding="UTF-8"?>
<office:document-content
  xmlns:office="urn:oasis:names:tc:opendocument:xmlns:office:1.0"
  xmlns:table="urn:oasis:names:tc:opendocument:xmlns:table:1.0"
  xmlns:text="urn:oasis:names:tc:opendocument:xmlns:text:1.0"
  xmlns:fo="urn:oasis:names:tc:opendocument:xmlns:xsl-fo-compatible:1.0"
  office:version="1.3">
  <office:body>
    <office:spreadsheet>
      <table:table table:name="Wallpapers">
        <table:table-column table:number-columns-repeated="3"/>
        """ + "\n        ".join(rows_xml) + """
      </table:table>
    </office:spreadsheet>
  </office:body>
</office:document-content>"""

manifest_xml = """<?xml version="1.0" encoding="UTF-8"?>
<manifest:manifest xmlns:manifest="urn:oasis:names:tc:opendocument:xmlns:manifest:1.0">
  <manifest:file-entry manifest:full-path="/" manifest:media-type="application/vnd.oasis.opendocument.spreadsheet"/>
  <manifest:file-entry manifest:full-path="content.xml" manifest:media-type="text/xml"/>
</manifest:manifest>"""

out_path = "/home/ryu/Pictures/Wallpapers/MyWallpaper/wallpapers.ods"
with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED) as zf:
    zf.writestr("mimetype", "application/vnd.oasis.opendocument.spreadsheet",
                compress_type=zipfile.ZIP_STORED)
    zf.writestr("META-INF/manifest.xml", manifest_xml)
    zf.writestr("content.xml", content_xml)

print(f"📄  Fichier généré : {out_path}")
print(f"    Taille : {__import__('os').path.getsize(out_path):,} octets\n")

# ── Aperçu des 20 premières lignes ────────────────────────────────────────────
print(f"{'ID':>4}  {'ANCIEN NOM':<60}  NOUVEAU NOM")
print("-" * 130)
for r in rows[:20]:
    print(f"{r[0]:>4}  {r[1]:<60}  {r[2]}")
